### ISSUE TITLE
Foundry offers to downgrade the module

### ISSUE THREAD

**Issue by cs96and** [mawburn/foundry-user-latency#11] opened 2023-07-03 15:24 UTC
After upgrading to v2.0.2, when I do an update all in Foundry, it offers an updated manifest location for v1.3.9...

![image](https://github.com/mawburn/foundry-user-latency/assets/898086/c383be50-7a6b-4474-8a0e-605bbb2a02a8)

**Comment by mawburn** [comment] 2023-07-13 17:21
Should be fixed. They changed up the way we release things apparently.

Can any of you confirm?
cc: @cs96and @krobibero @frederik-b @thejoester @mcdaddytalk

**Comment by frederik-b** [comment] 2023-07-13 17:29
<img width="464" alt="image" src="https://github.com/mawburn/foundry-user-latency/assets/957924/1be1f40f-dd01-46da-84f5-0c95db132277">






This is on a foundry 10 installation.
I can check again tomorrow.

**Comment by mawburn** [comment] 2023-07-13 17:40
Ugg annoying. Thanks. If it persists I'll reach out to someone on Discord. It's not an issue with my code, just the way it's versioned on their side. I think I screwed it up.

**Comment by mawburn** [comment] 2023-07-24 17:25
Any updates? Apologies, I wasn't able to reproduce this.

**Comment by kristianserrano** [comment] 2023-07-24 19:36
@cs96and I suspect you have a version of v2.0.2 that might have had a bad URL for the download. I recommend uninstalling the module and reinstalling it from the package directory in Foundry.

**Comment by OberstK** [comment] 2023-07-30 11:09
@mawburn issue persist. A reinstall does not help as it still only offers 1.3.9 instead of 2.0.2 in the client

**Comment by kristianserrano** [comment] 2023-07-30 14:14
Are you using Foundry VTT on The Forge by chance?

**Comment by mawburn** [comment] 2023-07-30 20:44
Thanks @OberstK. 

fwiw, these versions of functionally identical. The code base changed considerably, hence the major version bump, but the end user (including the GM) should not notice a difference.

**Comment by mawburn** [comment] 2023-07-30 20:47
@kristianserrano Thanks for the help but I actually use The Forge so the issue isn't there. 

![Screenshot 2023-07-30 at 4 46 02 PM (1)](https://github.com/mawburn/foundry-user-latency/assets/2829924/dfdb55c8-4ffd-468b-b631-4d67504e17ed)

However, the Foundry versioning shows this problem. This screenshot was made after the latest version bump. But that could (hopefully) be a caching issue.

<img width="919" alt="Screenshot 2023-07-30 at 5 06 45 PM" src="https://github.com/mawburn/foundry-user-latency/assets/2829924/d3414e91-266e-4814-b7de-8f24cee8ab95">

But the versions are listed below:

<img width="1147" alt="Screenshot 2023-07-30 at 4 56 53 PM" src="https://github.com/mawburn/foundry-user-latency/assets/2829924/1a5b9b9c-484e-46f6-8d72-b1f3b84fb308">

**Comment by kristianserrano** [comment] 2023-07-30 21:11
That "caching" issue was what made me think it was an issue on The Forge. It's happened with other modules in the past.

**Comment by mawburn** [comment] 2023-07-30 21:13
Yeah, it took a while for the version bump to get populated there but it actually gets it right.

I posted in the Discord and made an issue in their repo.

**Comment by mawburn** [comment] 2023-07-31 19:17
So this is an issue on Foundry's side. They get tripped up when there is a `v` in the version string. But are refusing to admit to that it's an issue with their code.

https://github.com/foundryvtt/foundryvtt/issues/9862

I removed it in their release packages and the admin is showing the proper version now. 

<img width="899" alt="Screenshot 2023-07-31 at 3 14 55 PM" src="https://github.com/mawburn/foundry-user-latency/assets/2829924/05971a71-e644-48b1-87ca-14682fd5517f">

You may need to uninstall and reinstall the package. 

If this continues to be an issue, file the bug on their side. 

Some version of this plugin should really be a feature in the native client anyway since it's simple and is able to help users figure out problems with their game.

**Closed as completed by mawburn** 2023-07-31 19:17 UTC
